### ISSUE TITLE
Running issue...

### ISSUE THREAD

**Issue by FrankZhao1999** [labmlai/labml#113]
Still updating app.labml.ai, please wait for it to complete...
cannot visulize when I ran the colab example
![image](https://github.com/labmlai/labml/assets/97596450/f7672be7-7c13-4d3f-aa55-fb4c7928064e)

**Comment by vpj** [comment]
Fixed the warning messages in https://github.com/labmlai/labml/commit/6eb3d3c0e09e46570d2b464208a136af66ac554d

You need to start your own labml server https://github.com/labmlai/labml/tree/master/app 

We unfortunately had to shutdown the free server due to costs.
