### ISSUE TITLE
Failed to connect server

### ISSUE THREAD

**Issue by Zedbzzb** [labmlai/labml#158]
Hello,when i start the experiment,the labml warning"[WinError 10061] The connection could not be made due to the target computer's positive rejection. Failed to connect: http://localhost:5005/api/v1/track?“is coming and i can't use the command labml app-server to start labml server in Anaconda Prompt,although i have installed the package named labml-app

**Comment by f-hy** [comment]
You should start app-server actually by
```shell
labml app-server
```
however, when it comes to the windows python venv, it can't be started:
```log
(.venv) (base) PS E:\data\frid\python\codes\adlpi> labml app-server
The filename, directory name, or volume label syntax is incorrect.
```

**Comment by f-hy** [comment]
when after start the app-server, you can connect to http://localhost:5005/api/v1/

**Comment by hnipun** [comment]
Sorry, we currently don't have any plans to provide support for it on Windows. Thanks.

**Comment by hnipun** [comment]
Sorry, we currently don't have any plans to provide support for it on Windows. Thanks.
