### ISSUE TITLE
The app-server don't send any response

### ISSUE THREAD

**Issue by li1553770945** [labmlai/labml#201]
I opened a server using the `labml app-server` command, however opening `localhost:5005` from a browser keeps waiting, using `wget http://localhost:5005/api/v1/`, it keeps displaying

```
--2024-04-02 14:59:16 -- http://localhost:5005/api/v1/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:5005... connected.
HTTP request sent, awaiting response... 
```

The output of app-server is as follows:

```
[2024-04-02 14:59:00 +0800] [822732] [INFO] Starting gunicorn 21.2.0
[2024-04-02 14:59:00 +0800] [822732] [INFO] Listening at: http://0.0.0.0:5005 (822732)
[2024-04-02 14:59:00 +0800] [822732] [INFO] Using worker: uvicorn.workers.
[2024-04-02 14:59:00 +0800] [822733] [INFO] Booting worker with pid: 822733
[2024-04-02 14:59:03 +0800] [822732] [INFO] Handling signal: winch
[2024-04-02 14:59:30 +0800] [822732] [CRITICAL] WORKER TIMEOUT (pid:822733)
[2024-04-02 14:59:31 +0800] [822732] [ERROR] Worker (pid:822733) was sent code 134!
[2024-04-02 14:59:31 +0800] [823163] [INFO] Booting worker with pid: 823163
```

**Comment by hnipun** [comment]
I assume you're running the server on your local machine. Could you please check the memory/CPU usage while the server is running? The FastAPI server logs you provided indicate that error code 134 might be due to insufficient resources.

**Comment by li1553770945** [comment]
Hello, I am running this on my server with ssh. My CPU model is `Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz`, RAM is `128GB` and I am not running any other resource consuming applications.

I have observed the CPU and memory usage using `htop` and it looks like there are no anomalies in resource usage.

![image](https://github.com/labmlai/labml/assets/55867654/98ca4ab3-3c21-478f-be33-8d7ebc9bb1f3)

**Comment by hnipun** [comment]
Thanks,  could you please verify if MongoDB is installed and running on the default port (27017)? Additionally, could you provide details about the operating system?

**Comment by li1553770945** [comment]
Sorry, I observed the service in running state after installing MongoDB and assumed it was working fine, when in fact for some reason it quit unexpectedly. I restarted MongoDB and it worked.

Thank you for your help, this is now resolved but I still have two minor issues.

## 1. The first one is that I have configured the following configuration item in `.labml.yaml`, based on the [pypi](https://pypi.org/project/labml-app/) and [guides](https://github.com/labmlai/labml/blob/master/guides/labml_yaml_file.md):

```
web_api: 'http://localhost:5005/api/v1/track?'
```

But it shows 

```
LABML WARNING: Method Not Allowed 405: http://localhost:5005/api/v1/track?run_uuid=0b405056f0c811ee902521fc9abb02ad&rank=0&world_ size=0&labml_version=0.4.168.
```

I'm guessing it might be caused by different versions of different components of labml not adapting?

![image](https://github.com/labmlai/labml/assets/55867654/07482049-2b8f-4f92-9b29-4f7699b47de9)

## 2. The second question is, if I have completed a training session and the logs folder has not been artificially modified since the training, can I still see the entire training process from the browser?

![image](https://github.com/labmlai/labml/assets/55867654/395c5cc3-919b-401c-a88c-a5dcc7bec2c0)

**Comment by hnipun** [comment]
Glad that your problem is solved now.

1. I think you need to update the **labml** pip package
2. All the data to view training progress in the browser is kept in a mongodb database, so you should able to view the training progress in the browser, But it should also save in the log folder.

**Comment by li1553770945** [comment]
I have solvedThank you for your help.

I have solved my problem, but I have some suggestions. The latest version of labml-nn is currently 0.4.136, which is incompatible with the latest versions of labml (0.5.1) and labml-app (0.5.1). If the user uses `pip install labml-app labml labml-nn` for installation, it will result in an exception.

Also, different versions of labml use different configuration files, e.g. `web_api` in some versions, `app_url` in others, and I haven't found a complete documentation on which configuration file should be used for that version, and I'm not sure what the URL of that configuration file should be for each version! I'm not sure what the URL of that configuration item should be for each version.

Your work has greatly facilitated my development tasks, thank you again!

**Comment by hnipun** [comment]
We have updated the [Readme.md](https://github.com/labmlai/labml) with the latest configuration.

**Comment by li1553770945** [comment]
> We have updated the [Readme.md](https://github.com/labmlai/labml) with the latest configuration.

Yes, but the instructions in README.md apply to the latest version of labml and labml-app. However, the latest version of labml-nn does not adapt to the latest version of labml.

I am trying to run [switch transfomers](https://github.com/labmlai/annotated_deep_learning_paper_implementations/tree/master/labml_nn/transformers/switch), and if I use the latest version of labml-nn as well as the latest version of labml, these codes report an error, so I have to use an older version of labml as well as an older version of labml-app, but I don't know where the documentation is for these older versions.

**Comment by hnipun** [comment]
@vpj 

> > We have updated the [Readme.md](https://github.com/labmlai/labml) with the latest configuration.
> 
> Yes, but the instructions in README.md apply to the latest version of labml and labml-app. However, the latest version of labml-nn does not adapt to the latest version of labml.
> 
> I am trying to run [switch transfomers](https://github.com/labmlai/annotated_deep_learning_paper_implementations/tree/master/labml_nn/transformers/switch), and if I use the latest version of labml-nn as well as the latest version of labml, these codes report an error, so I have to use an older version of labml as well as an older version of labml-app, but I don't know where the documentation is for these older versions.
