### ISSUE TITLE
labml.experiment' has no attribute 'add_pytorch_models'

### ISSUE THREAD

**Issue by jacklisp** [labmlai/labml#207]
when I make a fun call 
```
experiment.add_pytorch_models(dict(model=conf.model))
```
But it show the AttributeError: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_1766/1758481103.py in <module>
----> 1 experiment.add_pytorch_models(dict(model=conf.model))

AttributeError: module 'labml.experiment' has no attribute 'add_pytorch_models'

**Comment by vpj** [comment]
This is not available in the new api
