### ISSUE TITLE
Network error in comparison section

### ISSUE THREAD

**Issue by sviperm** [labmlai/labml#66]
Issue: when runs were added to comparison section then were deleted, there is network error + 404 error

![image](https://user-images.githubusercontent.com/36929696/123227592-660e3480-d4dd-11eb-9d01-6e93965ccfca.png)
![image](https://user-images.githubusercontent.com/36929696/123227995-ca30f880-d4dd-11eb-8861-35fbd9cdd85a.png)

[Run in app.labml.ai](https://app.labml.ai/run/c8272abcbca911eb8f8e04d4c4213fd1)

How to reproduce: create 2 runs, add one to another to compare, then delete run which was added

Tested in incognito-mode tab, so this is no cache/cookies problem

**Comment by vpj** [comment]
https://github.com/labmlai/app

**Comment by vpj** [comment]
@nmasnadithya reminder

**Comment by nmasnadithya** [comment]
Got caught up with some work. Let me check this

**Comment by vpj** [comment]
@nmasnadithya reminder
