### ISSUE TITLE
Some private runs visible on homepage before login or refresh

### ISSUE THREAD

**Issue by adrien1018** [labmlai/labml#97]
The current app.labml.ai homepage somehow displays some private runs that are not supposed to be visible to public when visiting the website first time, even without login. It only asked for login after one refresh or revisit.

**Comment by nmasnadithya** [comment]
There was a bug that made the unauthenticated users visit a testing account in their initial visit. What you saw wasn't private experiments but experiments that were associated with that testing account. We fixed this issue a couple of weeks ago.

Sorry for the late reply.
