### ISSUE TITLE
How can I restarted thread again?

### ISSUE THREAD

**Issue by AI-ML-Enthusiast** [labmlai/labml#98]
I try to use labml in my project. I run my code, it produced error. Try to fix it and run again but in the second time run it produced the following error:
--------------------------------------------------------------------------
```

RuntimeError                              Traceback (most recent call last)

[<ipython-input-42-c44305bd3335>](https://localhost:8080/#) in <module>()
    428 #
    429 if __name__ == '__main__':
--> 430     main()

10 frames

[/usr/lib/python3.7/threading.py](https://localhost:8080/#) in start(self)
    846 
    847         if self._started.is_set():
--> 848             raise RuntimeError("threads can only be started once")
    849         with _active_limbo_lock:
    850             _limbo[self] = self

RuntimeError: threads can only be started once
```
I think the previous thread stills running!
How can I reset/kill/restart the thread to run again from starting point?

**Comment by vpj** [comment]
You are running it from a notebook right? If you restart the kernel it'll stop the thread.

We will see if we can solve this problem when running on notebooks.
